### ISSUE TITLE
Extra space when coloring cell

### ISSUE THREAD

**Issue by Flythe** [krlmlr/Excel2LaTeX#12]
Coloring a single cell adds an extra space to the cell's content, see [here](https://github.com/krlmlr/Excel2LaTeX/blob/25cb2bc820045a9a1b129254ffd7e1c328937f1d/src/CModel.cls#L533). This makes the content not line up with the rest of the table's content.

**Comment by chelh** [comment]
This will be fixed in the next version, thanks!
