### ISSUE TITLE
How to fill in caption?

### ISSUE THREAD

**Issue by enoordam** [krlmlr/Excel2LaTeX#14]
How can you get Excel2LaTeX to fill in the caption automatically? I can't seem to figure this out. I don't want to have to manually edit the output each time.

**Comment by krlmlr** [comment]
Can you write a .tex file `generated.tex` and include it via `\input{}`, like this:

```tex
\begin{table}
  \input{generated}
  \caption{Your caption}
\end{table}
```

?

**Comment by enoordam** [comment]
Yes I realize now that's the best way to do it, just export without the table environment. 
Thanks! 


-------- Original Message --------

**Comment by chenqiuyuan** [comment]
I think it will be more elegant if we can choose to fill the caption and the label.

Maybe an easy workaround is to enable editing the results in the box (or something like a template).
