### ISSUE TITLE
Excel2LaTeX on Excel 2016 Mac-version gives error

### ISSUE THREAD

**Issue by dsiepman** [krlmlr/Excel2LaTeX#15]
Since I removed the `.xla-file` I can't seem to get the add-in working again. When I placed it back and re-opened it keeps giving the following error when I try to use it: 
> A document with the name 'Excel2LaTeX.xla' is already open. You cannot open two documents with the same name, even if the documents are in different folders. To open the second document, either close the document that's currently open, or rename one of the documents.

I have tried to turn-off, or completely delete the extension from the Excel add-in list (`Tools > Excel add-ins...`). This sadly does not resolve the issue.

As of now the only clear solution to me is to re-install Excel on my Mac.  Does somebody know if there is anything else that I can do?

**Comment by chelh** [comment]
Could you try going into VBA and running `Application.Workbooks("Excel2LaTeX.xla").Path`, then, if that gives you a result, looking in that directory?

**Comment by dsiepman** [comment]
Running that command that you mentioned proved more difficult as I have not been able to do it.  I don't know if it is just me, but the VBA environment in Excel on Mac seems majorly limited and buggy in my opinion.

Even though I could not run the command I have been able to fix the problem by removing `com.microsoft.Excel` folder in my `Library/Containers` folder.

Thanks anyway for your reply!

**Comment by vmarquar** [comment]
@dsiepman could you please specify the path where you removed the file? It seems that I have the same problem as you but I can't find the file/folder...
