### ISSUE TITLE
copy to clipboard does not work in Excel 2013

### ISSUE THREAD

**Issue by milesandnick** [krlmlr/Excel2LaTeX#3]
copy to clipboard does not work in Excel 2013

**Comment by chelh** [comment]
Try this: [Excel2LaTeX_NewClipboardCode.zip](https://github.com/krlmlr/Excel2LaTeX/files/386292/Excel2LaTeX_NewClipboardCode.zip)

**Comment by milesandnick** [comment]
I have tested, and it works well. Thanks.

2016-07-27 22:25 GMT+08:00 Chelsea Hughes <notifications@github.com>:

**Comment by chelh** [comment]
Watch for a new release, since I've been working on some improvements to the code I added this morning (Unicode support, removal of a 4kB size limit, probably some others&hellip;)
