### ISSUE TITLE
Error VBA '13'

### ISSUE THREAD

**Issue by ccsric** [krlmlr/Excel2LaTeX#5]
Macro debug:

Public Function NewModel() As IModel
=>    Set NewModel = New CModel
End Function

**Comment by chelh** [comment]
Do you have time for a TeamViewer session today?

**Comment by chelh** [comment]
I think [this new build](https://github.com/krlmlr/Excel2LaTeX/files/399784/Excel2LaTeX.zip) might fix it, but if so, I need to know what version of Excel you're running, and what you get if you enter `Application.Version` into the VBE's **Immediate** window.

**Comment by ccsric** [comment]
Hi,

immediate window :

Yes, the new build fixes the issue !

Thanks for you support.
