### ISSUE TITLE
Not Working in Excel 15.24 for Mac (Spanish)

### ISSUE THREAD

**Issue by diegojavierjimenez** [krlmlr/Excel2LaTeX#6]
I tried to open this in Excel 2016 for Mac (version 15.24) in Spanish and it says "El argumento o la llamada a procedimiento no es válida" which I guess is the translation to "Invalid procedure call or argument". When trying to debug it highlights the following line in "ThisWorkbook":

`Private Sub Workbook_Open()`

Here is a print screen (sorry for Spanish):

<img width="994" alt="captura de pantalla 2016-08-04 a las 7 04 30 p m 1" src="https://cloud.githubusercontent.com/assets/6239054/17422315/57058420-5a76-11e6-930c-3c8ea68ed01e.png">

**Comment by chelh** [comment]
Might you have time for a TeamViewer session?

**Comment by diegojavierjimenez** [comment]
Yes, unfortunately not this weekend as I am out of office (where the bug
happens). Can we schedule it for Monday?

**Comment by chelh** [comment]
Yes. 5 p.m. UTC?

**Comment by diegojavierjimenez** [comment]
Sounds good to me. 5 pm UTC - (noon in Mexico City time).

**Comment by chelh** [comment]
Ready when you are...

**Comment by diegojavierjimenez** [comment]
Hello, 

Thanks for the reminder! Give me 5 mins I am installing TeamViewer.

Diego


El 8 de agosto de 2016 a las 12:04:41 p.m., Chelsea Hughes (notifications@github.com) escribió:

Ready when you are...

**Comment by diegojavierjimenez** [comment]
Done, what do I have to give you?

Diego


El 8 de agosto de 2016 a las 12:06:08 p.m., Diego Javier Jiménez (djavierjh@gmail.com) escribió:

Hello, 

Thanks for the reminder! Give me 5 mins I am installing TeamViewer.

Diego


El 8 de agosto de 2016 a las 12:04:41 p.m., Chelsea Hughes (notifications@github.com) escribió:

Ready when you are...

**Comment by chelh** [comment]
Launch TeamViewer and give me your **ID** and **Password**, under the **Allow Remote Control** section.

**Comment by diegojavierjimenez** [comment]
ID: 861 873 682
Pwd: 13cn8y

Diego


El 8 de agosto de 2016 a las 12:17:43 p.m., Chelsea Hughes (notifications@github.com) escribió:

Launch TeamViewer and give me your ID and Password, under the Allow Remote Control section.

**Comment by chelh** [comment]
Try [this build](https://github.com/krlmlr/Excel2LaTeX/files/407494/Excel2LaTeX.zip) please.

**Comment by chelh** [comment]
I came out with a more general fix, so please try [this new build](https://github.com/krlmlr/Excel2LaTeX/files/410966/excel2latex.zip) when you next have an opportunity. It seems to work on other versions of Excel for Mac.

**Comment by diegojavierjimenez** [comment]
I am home (without the laptop where Mac 2016 is) and I just opened the
build. Good news, it works on Mac 2013 Spanish (2014? I don't know which
one it is)! I will let you know on the other computer once I am able to try
it there.

Thanks!

**Comment by diegojavierjimenez** [comment]
Update: it seems to work on Office 2016! I have tested it once and it works. Will continue testing it to see if everything is okay.

Diego


En 10 de agosto de 2016 en 11:18:48, Diego Jimenez (djavierjh@gmail.com) escrito:

I am home (without the laptop where Mac 2016 is) and I just opened the build. Good news, it works on Mac 2013 Spanish (2014? I don't know which one it is)! I will let you know on the other computer once I am able to try it there.

Thanks!

El mié., 10 ago. 2016 a las 6:55, Chelsea Hughes (<notifications@github.com>) escribió:
I came out with a more general fix, so please try this new build when you next have an opportunity. It seems to work on other versions of Excel for Mac.
