### ISSUE TITLE
Cellcolor

### ISSUE THREAD

**Issue by paul-git** [krlmlr/Excel2LaTeX#8]
Thanks for this great tool! It saved me a lot of hours. There seems to be a minor bug in the \cellcolor: 

> ! Package color Error: Argument `776' not in range [0,1].

Maybe this is only a German/European issue, because of the flipped decimal point / comma system. In that case an option would be great to choose how to export it :)

The generated output looks like this:
`\cellcolor[rgb]{0,776, 0,878, 0,706}`
and should look like this:
`\cellcolor[rgb]{0.776, 0.878, 0.706}`
(Notice the decimal point instead of comma).

For now a quick workaround is achievable with the following regEx (e. g. in Notepad++):
`\\cellcolor\[rgb\]\{0,([0-9]+), 0,([0-9]+), 0,([0-9]+)\}`
Replace with:
`\\cellcolor\[rgb\]\{0.\1, 0.\2, 0.\3\}`

Thanks again,
Paul

**Comment by chelh** [comment]
Replace the `ColorToRGB()` function in `CModel` with the following:

    Private Function ColorToRGB(ByVal Color&) As String
        ColorToRGB = Printf("%1, %2, %3", Str$(Round((Color And &HFF&) / 255, 3)), _
                    Str$(Round((Color And &HFF00&) / &H100 / 255, 3)), _
                    Str$(Round((Color And &HFF0000) / &H10000 / 255, 3)))
    End Function

Expect a new version in the coming week with this change.
